spring.application.name=realcrypto

# MySQL DB 설정 (Docker 컨테이너 연동)
spring.datasource.url=jdbc:mysql://localhost:3306/realcrypto?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root1234

# JPA 및 하이버네이트 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# 거래소 API 주소 설정
upbit.api.url=https://api.upbit.com/v1/ticker
binance.api.url=https://api.binance.com/api/v3/ticker/24hr